name: one_shot_glory
description: 'One Shot Glory is a plugin that allows you to kill a player with one shot.'
version: '0.1.3'
main: com.karasu256.one_shot_glory.One_Shot_Glory
api-version: '1.21'
authors: [ Hashibutogarasu ]
commands:
    osg:
        description: 'Base command for One Shot Glory plugin'
        usage: '/osg <subcommand>'
        permission: 'one_shot_glory.command'
        permission-message: 'You do not have permission to use this command.'
        aliases: [one_shot_glory]
permissions:
    one_shot_glory.command:
        description: 'Allows using the base osg command'
        default: true
    osg.config:
        description: 'Allows using the config subcommand'
        default: op
    osg.reload:
        description: 'Allows using the reload subcommand'
        default: op
    osg.start:
        description: 'Allows using the start subcommand'
        default: op
    osg.stop:
        description: 'Allows using the stop subcommand'
        default: op