name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle Wrapper
        run: ./gradlew build
        
      - name: Find JAR files
        id: find-jars
        shell: bash
        run: |
          echo "jar_files=$(find build/libs/ -name "*.jar" -type f | tr '\n' ' ')" >> $GITHUB_OUTPUT
          echo "Found JARs: $(find build/libs/ -name "*.jar" -type f | wc -l)"

      - name: Upload JAR files individually
        if: ${{ steps.find-jars.outputs.jar_files != '' }}
        run: |
          for jar_file in ${{ steps.find-jars.outputs.jar_files }}; do
            if [ -f "$jar_file" ]; then
              filename=$(basename "$jar_file")
              artifact_name="${filename%.jar}"
              
              echo "Uploading $filename as artifact: $artifact_name"
              
              gh workflow run .github/workflows/upload-single-jar.yml \
                -f jar_path="$jar_file" \
                -f artifact_name="$artifact_name"
            else
              echo "::warning::File not found: $jar_file"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
